### ISSUE TITLE
Weird behaviour when setting height

### ISSUE THREAD

**Issue by vesper8** [okijhhyu/element-tiptap-vue3#11]
Hello! First of all HUGE THANK YOU for fixing the original project.. it was such a pain to find a nice version of tiptap that already has all the icons working in the menubar that doesn't force you to use something like Quasar Framework.

Your version works amazing!! Big thanks for your initiative!

I noticed that when setting the width and height like this:

```

  <el-tiptap
    lang="en"
    ref="editor"
    output="html"
    :extensions="allExtensions"
    v-model:content="content"
    width="100%"
    height="50vh"
  />
```

The editor appears to grow in height, however when you try to focus inside the blank space to start writing.. it will not allow you to click on most of the blank space.. it only works if you click near the top.. unsure what is going on.. it's like the outer editor grows in height but not the inner editor.

Would be great if you could fix this! : )

**Comment by okijhhyu** [comment]
On next week i wiil see it.

**Comment by okijhhyu** [comment]
https://github.com/okijhhyu/element-tiptap-vue3/releases/tag/v1.1.3
