### ISSUE TITLE
Unable to add @tiptap/extension-gapcursor extension

### ISSUE THREAD

**Issue by vesper8** [okijhhyu/element-tiptap-vue3#12]
I'm trying to add the https://tiptap.dev/api/extensions/gapcursor/ extension to element-tiptap and I get an error `Adding different instances of a keyed plugin`

I need to add this extension because currently it's impossible to put the cursor under or above a table inside tiptap

Could you add it please? Or else tell me how I can add it myself? I don't really understand the error message.

Many thanks!

**Comment by okijhhyu** [comment]
No problem on next week, it wiil be added

**Comment by okijhhyu** [comment]
https://github.com/okijhhyu/element-tiptap-vue3/releases/tag/v1.1.3

**Comment by okijhhyu** [comment]
Should i add dropcursor ?https://tiptap.dev/api/extensions/dropcursor

**Comment by vesper8** [comment]
@okijhhyu yes I think it's a very useful one as well which is usually included in their starterkit so yes I'd say go ahead!
