### ISSUE TITLE
The link on the toolbar always placed first

### ISSUE THREAD

**Issue by koko469** [okijhhyu/element-tiptap-vue3#22]
Hello, there's a question. Why is the link on the toolbar always placed first ,How should I solve it.

**Comment by okijhhyu** [comment]
Today try to fix it, in bad way it will be fixed tomorrow.

**Comment by okijhhyu** [comment]
new version [1.1.9](https://github.com/okijhhyu/element-tiptap-vue3/releases/tag/v.1.1.9)

**Comment by koko469** [comment]
> 新版本 [1.1.9](https://github.com/okijhhyu/element-tiptap-vue3/releases/tag/v.1.1.9)

The link button on the top toolbar has been fixed, but the Bubble menu has not been fixed yet

**Comment by okijhhyu** [comment]
> > 新版本 [1.1.9](https://github.com/okijhhyu/element-tiptap-vue3/releases/tag/v.1.1.9)
> 
> The link button on the top toolbar has been fixed, but the Bubble menu has not been fixed yet

Fixed in version [v.1.1.10](https://github.com/okijhhyu/element-tiptap-vue3/releases/tag/v.1.1.10) 🎉🎉🎉

**Comment by koko469** [comment]
> Fixed in version [v.1.1.10](https://github.com/okijhhyu/element-tiptap-vue3/releases/tag/v.1.1.10) 🎉🎉🎉
Okay, thank you very much🎉🎉🎉
