### ISSUE TITLE
paste image event

### ISSUE THREAD

**Issue by koko469** [okijhhyu/element-tiptap-vue3#34]
Hello author, can you add a paste image event? As the format of the paste image is base64, I would like to upload the paste image to a remote server.

**Comment by okijhhyu** [comment]
Hi, did u try  to use uploadRequest?
```vue
Image,configure({
     uploadRequest (file: File): Promise<url> {
       // upload file to Google Cloud Storage
       return Promise.resolve(url); // return a Promise with your file source url
     },
  })```

**Comment by koko469** [comment]
> Hi, did u try to use uploadRequest?
Yes, but this can only be done by clicking on "Upload from local" in the menu bar. If I want to paste a picture from the editor (for example, after taking a screenshot), it won't invoke uploadRequest, and the format will still be base64.

**Comment by koko469** [comment]
I want to refer to [https://www.codemzy.com/blog/tiptap-pasting-images](tiptap-pasting-images) to solve the problem of pasting images, but I don't know how to use editorProps.

**Comment by okijhhyu** [comment]
try to use editorProps. https://github.com/okijhhyu/element-tiptap-vue3/compare/v.1.2.2...v.1.2.3

**Comment by koko469** [comment]
ok,thank

**Comment by okijhhyu** [comment]
if will be problems, write
